import { EmployeesReimbursementReports } from "../types/reimbursement";

type WeekKey = "week-1" | "week-2" | "week-3" | "week-4";

// Mock dataset scope: April 2026 (weekly)
export const mockEmployeesReimbursementReportsByWeek: Record<WeekKey, EmployeesReimbursementReports> = {
	"week-1": {
		records: [
			{ employeeId: "EMP-1012", firstname: "Dianne", lastname: "Aquino", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1009", firstname: "Noel", lastname: "Castillo", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1015", firstname: "Arvin", lastname: "Cruz", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1001", firstname: "John", lastname: "Dela Cruz", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1018", firstname: "Alyssa", lastname: "Domingo", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1010", firstname: "Jessa", lastname: "Flores", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1006", firstname: "Liza", lastname: "Garcia", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1004", firstname: "Angela", lastname: "Lim", totalAmountReimbursed: 1800 },
			{ employeeId: "EMP-1014", firstname: "Patricia", lastname: "Lopez", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1008", firstname: "Carla", lastname: "Mendoza", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1011", firstname: "Bryan", lastname: "Navarro", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1016", firstname: "Nina", lastname: "Ramos", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1003", firstname: "Paolo", lastname: "Reyes", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1013", firstname: "Kevin", lastname: "Salazar", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1002", firstname: "Maria", lastname: "Santos", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1017", firstname: "Cedric", lastname: "Tan", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1005", firstname: "Ramon", lastname: "Torres", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1019", firstname: "Gerald", lastname: "Uy", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1020", firstname: "Trisha", lastname: "Velasco", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1007", firstname: "Mark", lastname: "Villanueva", totalAmountReimbursed: 760 },
		],
		meta: { page: 1, limit: 20, total: 20 },
	},
	"week-2": {
		records: [
			{ employeeId: "EMP-1012", firstname: "Dianne", lastname: "Aquino", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1009", firstname: "Noel", lastname: "Castillo", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1015", firstname: "Arvin", lastname: "Cruz", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1001", firstname: "John", lastname: "Dela Cruz", totalAmountReimbursed: 1200 },
			{ employeeId: "EMP-1018", firstname: "Alyssa", lastname: "Domingo", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1010", firstname: "Jessa", lastname: "Flores", totalAmountReimbursed: 2800 },
			{ employeeId: "EMP-1006", firstname: "Liza", lastname: "Garcia", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1004", firstname: "Angela", lastname: "Lim", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1014", firstname: "Patricia", lastname: "Lopez", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1008", firstname: "Carla", lastname: "Mendoza", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1011", firstname: "Bryan", lastname: "Navarro", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1016", firstname: "Nina", lastname: "Ramos", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1003", firstname: "Paolo", lastname: "Reyes", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1013", firstname: "Kevin", lastname: "Salazar", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1002", firstname: "Maria", lastname: "Santos", totalAmountReimbursed: 950 },
			{ employeeId: "EMP-1017", firstname: "Cedric", lastname: "Tan", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1005", firstname: "Ramon", lastname: "Torres", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1019", firstname: "Gerald", lastname: "Uy", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1020", firstname: "Trisha", lastname: "Velasco", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1007", firstname: "Mark", lastname: "Villanueva", totalAmountReimbursed: 0 },
		],
		meta: { page: 1, limit: 20, total: 20 },
	},
	"week-3": {
		records: [
			{ employeeId: "EMP-1012", firstname: "Dianne", lastname: "Aquino", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1009", firstname: "Noel", lastname: "Castillo", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1015", firstname: "Arvin", lastname: "Cruz", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1001", firstname: "John", lastname: "Dela Cruz", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1018", firstname: "Alyssa", lastname: "Domingo", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1010", firstname: "Jessa", lastname: "Flores", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1006", firstname: "Liza", lastname: "Garcia", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1004", firstname: "Angela", lastname: "Lim", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1014", firstname: "Patricia", lastname: "Lopez", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1008", firstname: "Carla", lastname: "Mendoza", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1011", firstname: "Bryan", lastname: "Navarro", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1016", firstname: "Nina", lastname: "Ramos", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1003", firstname: "Paolo", lastname: "Reyes", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1013", firstname: "Kevin", lastname: "Salazar", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1002", firstname: "Maria", lastname: "Santos", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1017", firstname: "Cedric", lastname: "Tan", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1005", firstname: "Ramon", lastname: "Torres", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1019", firstname: "Gerald", lastname: "Uy", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1020", firstname: "Trisha", lastname: "Velasco", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1007", firstname: "Mark", lastname: "Villanueva", totalAmountReimbursed: 0 },
		],
		meta: { page: 1, limit: 20, total: 20 },
	},
	"week-4": {
		records: [
			{ employeeId: "EMP-1012", firstname: "Dianne", lastname: "Aquino", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1009", firstname: "Noel", lastname: "Castillo", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1015", firstname: "Arvin", lastname: "Cruz", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1001", firstname: "John", lastname: "Dela Cruz", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1018", firstname: "Alyssa", lastname: "Domingo", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1010", firstname: "Jessa", lastname: "Flores", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1006", firstname: "Liza", lastname: "Garcia", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1004", firstname: "Angela", lastname: "Lim", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1014", firstname: "Patricia", lastname: "Lopez", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1008", firstname: "Carla", lastname: "Mendoza", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1011", firstname: "Bryan", lastname: "Navarro", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1016", firstname: "Nina", lastname: "Ramos", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1003", firstname: "Paolo", lastname: "Reyes", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1013", firstname: "Kevin", lastname: "Salazar", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1002", firstname: "Maria", lastname: "Santos", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1017", firstname: "Cedric", lastname: "Tan", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1005", firstname: "Ramon", lastname: "Torres", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1019", firstname: "Gerald", lastname: "Uy", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1020", firstname: "Trisha", lastname: "Velasco", totalAmountReimbursed: 0 },
			{ employeeId: "EMP-1007", firstname: "Mark", lastname: "Villanueva", totalAmountReimbursed: 0 },
		],
		meta: { page: 1, limit: 20, total: 20 },
	},
};
