import { EmployeeReimbursementRequests } from "../types/reimbursement";
import {
	ReimbursementRequestStatus,
	ReimbursementType,
} from "@/app/(protected)/employee/reimbursement/types/reimbursement";

// Mock dataset scope: April 2026
export const mockEmployeesReimbursementRequests: EmployeeReimbursementRequests["requests"] = [
	{
		id: 1,
		employeeId: "EMP-1001",
		firstname: "John",
		lastname: "Dela Cruz",
		dateSubmitted: "2026-04-11T09:00:00.000Z",
		type: ReimbursementType.FOOD,
		amountRequested: 1200,
		amountApproved: 0,
		reason: "Client lunch meeting",
		attachment: "receipt-food-1001.jpg",
		status: ReimbursementRequestStatus.PENDING,
	},
	{
		id: 2,
		employeeId: "EMP-1002",
		firstname: "Maria",
		lastname: "Santos",
		dateSubmitted: "2026-04-10T14:20:00.000Z",
		type: ReimbursementType.TRANSPORTATION,
		amountRequested: 950,
		amountApproved: 950,
		reason: "Ride-hailing for site visit",
		attachment: "receipt-transport-1002.jpg",
		status: ReimbursementRequestStatus.APPROVED,
	},
	{
		id: 3,
		employeeId: "EMP-1003",
		firstname: "Paolo",
		lastname: "Reyes",
		dateSubmitted: "2026-04-09T11:45:00.000Z",
		type: ReimbursementType.OTHER,
		amountRequested: 2500,
		amountApproved: 0,
		reason: "Misc office supplies",
		attachment: "receipt-other-1003.jpg",
		status: ReimbursementRequestStatus.REJECTED,
	},
	{
		id: 4,
		employeeId: "EMP-1004",
		firstname: "Angela",
		lastname: "Lim",
		dateSubmitted: "2026-04-08T10:10:00.000Z",
		type: ReimbursementType.FOOD,
		amountRequested: 1800,
		amountApproved: 1800,
		reason: "Team lunch during client workshop",
		attachment: "receipt-food-1004.jpg",
		status: ReimbursementRequestStatus.APPROVED,
	},
	{
		id: 5,
		employeeId: "EMP-1005",
		firstname: "Ramon",
		lastname: "Torres",
		dateSubmitted: "2026-04-07T15:05:00.000Z",
		type: ReimbursementType.TRANSPORTATION,
		amountRequested: 1100,
		amountApproved: 0,
		reason: "Airport transfer for business trip",
		attachment: "receipt-transport-1005.jpg",
		status: ReimbursementRequestStatus.PENDING,
	},
	{
		id: 6,
		employeeId: "EMP-1006",
		firstname: "Liza",
		lastname: "Garcia",
		dateSubmitted: "2026-04-06T08:40:00.000Z",
		type: ReimbursementType.OTHER,
		amountRequested: 2200,
		amountApproved: 0,
		reason: "Courier and printing expenses",
		attachment: "receipt-other-1006.jpg",
		status: ReimbursementRequestStatus.REJECTED,
	},
	{
		id: 7,
		employeeId: "EMP-1007",
		firstname: "Mark",
		lastname: "Villanueva",
		dateSubmitted: "2026-04-05T09:55:00.000Z",
		type: ReimbursementType.TRANSPORTATION,
		amountRequested: 760,
		amountApproved: 760,
		reason: "Commute to external audit office",
		attachment: "receipt-transport-1007.jpg",
		status: ReimbursementRequestStatus.APPROVED,
	},
	{
		id: 8,
		employeeId: "EMP-1008",
		firstname: "Carla",
		lastname: "Mendoza",
		dateSubmitted: "2026-04-04T14:20:00.000Z",
		type: ReimbursementType.FOOD,
		amountRequested: 1350,
		amountApproved: 0,
		reason: "Client dinner after presentation",
		attachment: "receipt-food-1008.jpg",
		status: ReimbursementRequestStatus.PENDING,
	},
	{
		id: 9,
		employeeId: "EMP-1009",
		firstname: "Noel",
		lastname: "Castillo",
		dateSubmitted: "2026-04-03T16:10:00.000Z",
		type: ReimbursementType.OTHER,
		amountRequested: 980,
		amountApproved: 0,
		reason: "Small tools purchase",
		attachment: "receipt-other-1009.jpg",
		status: ReimbursementRequestStatus.REJECTED,
	},
	{
		id: 10,
		employeeId: "EMP-1010",
		firstname: "Jessa",
		lastname: "Flores",
		dateSubmitted: "2026-04-02T12:35:00.000Z",
		type: ReimbursementType.FOOD,
		amountRequested: 3000,
		amountApproved: 2800,
		reason: "Meals during multi-day training",
		attachment: "receipt-food-1010.jpg",
		status: ReimbursementRequestStatus.APPROVED,
	},
];
