import {
	ReimbursementRequestStatus,
	ReimbursementRequests,
	ReimbursementType,
} from "../types/reimbursement";

// Mock dataset scope: April 2026
export const mockReimbursementRequests: ReimbursementRequests = {
	requests: [
		{
			id: 1,
			employeeId: "EMP-1007",
			dateSubmitted: "2026-04-03T10:15:00.000Z",
			type: ReimbursementType.FOOD,
			amountRequested: 1200,
			amountApproved: 0,
			reason: "Client lunch meeting",
			attachment: "receipt-food-1.jpg",
			status: ReimbursementRequestStatus.PENDING,
		},
		{
			id: 2,
			employeeId: "EMP-1007",
			dateSubmitted: "2026-04-05T14:20:00.000Z",
			type: ReimbursementType.TRANSPORTATION,
			amountRequested: 950,
			amountApproved: 950,
			reason: "Ride-hailing for site visit",
			attachment: "receipt-transport-2.jpg",
			status: ReimbursementRequestStatus.APPROVED,
		},
		{
			id: 3,
			employeeId: "EMP-1007",
			dateSubmitted: "2026-04-08T11:40:00.000Z",
			type: ReimbursementType.OTHER,
			amountRequested: 2500,
			amountApproved: 0,
			reason: "Office supplies purchase",
			attachment: "receipt-other-3.jpg",
			status: ReimbursementRequestStatus.REJECTED,
		},
		{
			id: 4,
			employeeId: "EMP-1007",
			dateSubmitted: "2026-04-11T09:05:00.000Z",
			type: ReimbursementType.FOOD,
			amountRequested: 1800,
			amountApproved: 1800,
			reason: "Team meal during training",
			attachment: "receipt-food-4.jpg",
			status: ReimbursementRequestStatus.APPROVED,
		},
		{
			id: 5,
			employeeId: "EMP-1007",
			dateSubmitted: "2026-04-14T15:30:00.000Z",
			type: ReimbursementType.TRANSPORTATION,
			amountRequested: 1100,
			amountApproved: 0,
			reason: "Airport transfer",
			attachment: "receipt-transport-5.jpg",
			status: ReimbursementRequestStatus.PENDING,
		},
		{
			id: 6,
			employeeId: "EMP-1007",
			dateSubmitted: "2026-04-17T08:50:00.000Z",
			type: ReimbursementType.OTHER,
			amountRequested: 2200,
			amountApproved: 2200,
			reason: "Courier and printing expenses",
			attachment: "receipt-other-6.jpg",
			status: ReimbursementRequestStatus.APPROVED,
		},
		{
			id: 7,
			employeeId: "EMP-1007",
			dateSubmitted: "2026-04-21T13:10:00.000Z",
			type: ReimbursementType.FOOD,
			amountRequested: 1350,
			amountApproved: 0,
			reason: "Client dinner after presentation",
			attachment: "receipt-food-7.jpg",
			status: ReimbursementRequestStatus.REJECTED,
		},
		{
			id: 8,
			employeeId: "EMP-1007",
			dateSubmitted: "2026-04-24T16:25:00.000Z",
			type: ReimbursementType.TRANSPORTATION,
			amountRequested: 760,
			amountApproved: 760,
			reason: "Commute to external audit office",
			attachment: "receipt-transport-8.jpg",
			status: ReimbursementRequestStatus.APPROVED,
		},
	],
};
